AtlasCode.AsyncSections.Demos/Controllers/ComparisonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using AtlasCode.AsyncSections;

namespace Async.Controllers
{
    public class ComparisonController : AsyncSectionController
    {
        //
        // GET: /Comparison/

        public ActionResult Index()
        {
            return View();
        }

		public void AsyncAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(5000);
				ViewBag.Message = "5 second task complete";
				AsyncSection("Task1");
				AsyncManager.OutstandingOperations.Decrement();
			});

			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(2000);
				ViewBag.Message2 = "2 second task complete";
				AsyncSection("Task2");
				AsyncManager.OutstandingOperations.Decrement();
			});

			// Send down the view so far
			AsyncView();
		}

		public ActionResult AsyncCompleted()
		{
			return null;
		}

		public void NoAsyncAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(5000);
				AsyncManager.Parameters.Add("message1", "5 second task complete");			
				AsyncManager.OutstandingOperations.Decrement();
			});

			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(2000);
				AsyncManager.Parameters.Add("message2", "2 second task complete");	
				AsyncManager.OutstandingOperations.Decrement();
			});
		}

		public ActionResult NoAsyncCompleted(string message1, string message2)
		{
			ViewBag.Message = message1;
			ViewBag.Message2 = message2;
			return View();
		}

    }
}

AtlasCode.AsyncSections.Demos/Controllers/ConsoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AtlasCode.AsyncSections;
using System.Threading.Tasks;

namespace Async.Controllers
{
	public class ConsoleController : AsyncSectionController
    {
		public void IndexAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				for (int i = 0; i < 10; i++)
				{
					System.Threading.Thread.Sleep(1000);

					ViewBag.Message = "Iteration " + i;
					AsyncSection("Console");
				}

				ViewBag.Message = "Complete";
				AsyncSection("Console");

				AsyncManager.OutstandingOperations.Decrement();
			});

			// Send down the view so far
			AsyncView();
		}

		public ActionResult IndexCompleted()
		{
			return null;
		}
    }
}

AtlasCode.AsyncSections.Demos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Async.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AtlasCode.AsyncSections.Demos/Controllers/MinimumController.cs
using System.Web.Mvc;
using AtlasCode.AsyncSections;

namespace Async.Controllers
{
    public class MinimumController : AsyncSectionController
    {
        public ActionResult Index()
        {
			AsyncView(); // Return the view before the async loading starts
			System.Threading.Thread.Sleep(5000); // Pretend to load data
			AsyncSection("Task1"); // Render the AsyncSection
            return null; // Return null rather than a view because we have already rendered everything
        }
    }
}

AtlasCode.AsyncSections.Demos/Controllers/MultipleTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using StackExchange.Profiling;
using System.Reflection;
using System.IO;
using System.Web.WebPages;
using AtlasCode.AsyncSections;

namespace Async.Controllers
{
	public class MultipleTaskController : AsyncSectionController
	{
		public void IndexAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(2000); // Simulate something that takes a while to load data

				ViewBag.Message = "Data loaded from message task 1 after 2 seconds"; // Imagine we got this string from some database or service
				AsyncSection("Message1");

				AsyncManager.OutstandingOperations.Decrement();
			});

			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(1000); // Simulate something that takes a while to load data

				ViewBag.Message2 = "Data loaded from message task 2 after 1 second"; // Imagine we got this string from some database or service
				AsyncSection("Message2");

				AsyncManager.OutstandingOperations.Decrement();
			});

			// Send down the view so far
			AsyncView();
		}

		public ActionResult IndexCompleted()
		{
			return null;
		}

		public ActionResult Test()
		{
			return PartialView();
		}
	}
}

AtlasCode.AsyncSections.Demos/Controllers/ProgressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AtlasCode.AsyncSections;
using System.Threading.Tasks;

namespace Async.Controllers
{
	public class ProgressController : AsyncSectionController
    {
		public void IndexAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				for (int i = 0; i < 10; i++)
				{
					System.Threading.Thread.Sleep(1000);

					ViewBag.Message = "Iteration " + i;
					AsyncSection("Console");
				}

				ViewBag.Message = "Complete";
				AsyncSection("Console");

				AsyncManager.OutstandingOperations.Decrement();
			});

			// Send down the view so far
			AsyncView();
		}

		public ActionResult IndexCompleted()
		{
			return null;
		}
    }
}

AtlasCode.AsyncSections.Demos/Controllers/ScriptOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AtlasCode.AsyncSections;
using System.Threading.Tasks;

namespace Async.Controllers
{
	public class ScriptOrderController : AsyncSectionController
    {
		public void IndexAsync()
		{
			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(5000);
				ViewBag.Message = "5 second task complete";
				AsyncSection("Task1");
				AsyncManager.OutstandingOperations.Decrement();
			});

			// Do Something Async
			AsyncManager.OutstandingOperations.Increment();
			Task.Factory.StartNew(() =>
			{
				System.Threading.Thread.Sleep(2000);
				ViewBag.Message2 = "2 second task complete";
				AsyncSection("Task2");
				AsyncManager.OutstandingOperations.Decrement();
			});

			// Send down the view so far
			AsyncView();
		}

		public ActionResult IndexCompleted()
		{
			return null;
		}
    }
}

AtlasCode.AsyncSections.Demos/Views/Comparison/Async.cshtml
@{
	ViewBag.Title = "AsyncSectionController";
}

<h2>AsyncSectionController</h2>

@section Task1Async{ @*Async sections must have the Async suffix*@
<p>@ViewBag.Message</p>
}

@section Task2Async{ @*Async sections must have the Async suffix*@
	<p>@ViewBag.Message2</p>
}

AtlasCode.AsyncSections.Demos/Views/Comparison/Index.cshtml
@{
	ViewBag.Title = "Side by Side Comparison";
}

<style>
iframe
{
	float:left;
	border:1px solid black;
}
h3
{
	float:left;
	width:300px;
}
</style>

<h2>Side by Side Comparison</h2>

<p>In the iframes below, you can see the percieved speed difference between a standard AsyncController ans the AsyncSectionController</p>

<h3>AsyncController</h3><h3>AsyncSectionsController</h3>
<div style="clear:both;"></div>
<iframe width="300" height="400" src="@Url.Action("NoAsync")"></iframe>
<iframe width="300" height="400" src="@Url.Action("Async")"></iframe>

AtlasCode.AsyncSections.Demos/Views/Comparison/NoAsync.cshtml
@{
	ViewBag.Title = "AsyncController";
}

<h2>AsyncController</h2>

<p>@ViewBag.Message</p>
<p>@ViewBag.Message2</p>

AtlasCode.AsyncSections.Demos/Views/Console/Index.cshtml
@{
    ViewBag.Title = "Console";
}

<style>
.hidden
{
	display:none;
}
</style>

<h2>Console Log</h2>

<p>This shows a long running server process feeding back progress as steps</p>

<ul id="consoleList">
</ul>

@section ConsoleAsync{
<li transform-append="consoleList" transform-removeClass="hidden" class="hidden">@ViewBag.Message</li>
}

<div>Some example footer info</div>

AtlasCode.AsyncSections.Demos/Views/Home/Console.cshtml
@{
    ViewBag.Title = "Console";
}

<style>
.hidden
{
	display:none;
}
</style>

<h2>Console Log</h2>

<p>This shows a long running server process feeding back progress as steps</p>

<ul id="consoleList">
</ul>

@section ConsoleAsync{
<li transform-append="consoleList" transform-removeClass="hidden" class="hidden">@ViewBag.Message</li>
}

<div>Some example footer info</div>

AtlasCode.AsyncSections.Demos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to the AsyncSections demo project</h2>
<p>To understand instantly what AsyncSections are all about, check out the @Html.ActionLink("comparison demo", "Index", "Comparison")</p>

<h3>What problem do AsyncSections solve?</h3>
<p>Some serverside functions take a while to complete, this can cause IIS thread starvation, which is addressed by MVC's AsyncController. Great! :-)</p>
<p>However, from a user's perspective nothing changes. They still have to wait x seconds for the page to respond and are are usually stuck on a white page that looks like the server isnt doing anything :-(</p>
<p>That's where AsyncSections come in! Imagine if you could seperate your view into sections which contain the results of your long running functions. Now you can! These are seperated from normal document rendering to allow the page to load first, then load in the results when they are ready.</p>

<h3>When would I use an AsyncSection</h3>
<p>Whenever you are doing something on the server that takes a few seconds but you dont want to make the user wait before allowing them to use the site. For example...</p>
<ul>
	<li>Processing an imported spreadsheet</li>
	<li>Waiting for 3rd party APIs to respond</li>
	<li>Doing some processing on all records in the database</li>
	<li>Generating documents</li>
	<li>Bulk functions like emailing all users or creating notification records</li>
	<li>Updating the database schema of the site using an EF 4.3 data migration :-)</li>
	<li>Use your imagination</li>
</ul>
<p>In theory, any page that accesses the database could use an AsyncSection, especially if it runs multiple different queries that display their results in different areas of the page, like a KPI dashboard</p>

<h3>How do AsyncSections work?</h3>
<p>AsyncSections are standard MVC sections which are suffixed with "Async" but they dont get rendered to the page in the standard way.</p>

<p>There is a new AsyncSectionController which contains the new AsyncView() and AsyncSection() methods. These combined with the new RenderBodyAsync() helper will split the page into multiple render stages.</p>
<ol>
	<li>MasterPage is rendered up to the call to RenderBodyAsync()</li>
	<li>The body is rendered excluding anything in an AsyncSection</li>
	<li>A number of AsyncSections are rendered</li>
	<li>The last half of the MasterPage is rendered after the call to RenderBodyAsync()</li>
</ol>

<img src="@Url.Content("~/Content/AsyncSectionsBasics.png")" alt="AsyncSections Breakdown" />

<p>In the @Html.ActionLink("example above", "Index", "Minimum"), you will see that the element in the Task1Async section will be rendered after the example footer</p>

<h3>But wait... what if I want my section to load into a specific part of the page?</h3>
<p>Good point! AsyncSections will nativly only get rendered just after your RenderBodyAsync() call. In order to load content into specific parts of the page you will need to employ some kind of javascript based solution (or css if your design permits). For this reason I have also created a small helper library calles jsTransform which may get its own repo one day if it gets enough use. You can see this in action in the @Html.ActionLink("Multiple Tasks Demo", "Index", "MultipleTask")</p>
<p>jsTransform checks the page for new elements every 100ms until the document is ready. If the element has one of the transform attributes (transform-append, transform-replace or transform-removeClass) then it will act on the element and remove the attributes.</p>

<img src="@Url.Content("~/Content/ConsoleDemo.png")" alt="Console Demo Source" />

<p>In the example above you can see that there is an unordered list with an id of consoleList and the AsyncSection contains a list item that has a transform-append attribute with a value of consoleList. This will take the list item and append it to the unordered list as soon as the list item arrives on the page.</p>
<p>Because AsyncSections arrive after the page has first rendrered, they will appear to blink at the bottom of the page until jsTransform moves them to their desired position in the DOM. To get arround this, I have added a hidden class to the list item that gets removed once the item element is transformed. There are many different ways to solve this problem, but this is a quick way to get you started.</p>
<p>The jsTransform library is currently quite small and only contains 3 attributes, but it will grow over time as people need more from it. Or alternatively, you can use any javascript library you like, its up to you!</p>

<h3>Summary</h3>
<p>AsyncSections is a research project that contains a lot of reflection on the internals of MVC4 and should not really be used in a production environment. The idea was to show what was possible with a few small tweaks of the Rendering system and with a bit of luck, get something similar added to a roadmap for MVC5+</p>
<p>For this reason, this project will probably only ever have a <a href="https://nuget.org/packages/AtlasCode.AsyncSections">pre release NuGet package</a></p>
<p>Please show your support for this project by sharing it with others and letting the MVC team know you would like a feature like this in the future. Fingers crossed :-)</p>
<p>If you got this far, thank you for taking the time to read this document</p>

AtlasCode.AsyncSections.Demos/Views/Home/Progress.cshtml
@{
    ViewBag.Title = "Console";
}

<style>
.hidden
{
	display:none;
}
</style>

<h2>Console Log</h2>

<p>This shows a long running server process feeding back progress as current status</p>

<p>Current Step: <span id="message"></span></p>


@section ConsoleAsync{
<span id="message" transform-replace="message" transform-removeClass="hidden" class="hidden">@ViewBag.Message</span>
}

<div>Some example footer info</div>

AtlasCode.AsyncSections.Demos/Views/Minimum/Index.cshtml
@{
	Layout = "~/Views/Shared/_Minimum.cshtml";
}

<h2>Bare Minimum Example (wait 5 seconds)</h2>

@section Task1Async{
	<p>Asynchronously Loaded Data</p>
}

<p>Example Footer</p>

AtlasCode.AsyncSections.Demos/Views/MultipleTask/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
.hidden
{
	display:none;
}
</style>

<h2>Multiple Tasks</h2>

<p>This should be visible and selectable on the page while the rest loads</p>

<div id="message1" style="border: 2px solid Red; height:100px; width:600px;"></div>

<div id="message2" style="border: 2px solid Green; height:100px; width:600px;"></div>

<div id="tests" style="border: 2px solid Blue; width:600px;"></div>

<div transform-append="tests">RenderAction NonAsync @{Html.RenderAction("Test");}</div>
<div transform-append="tests">Action NonAsync @Html.Action("Test")</div>

@section Message1Async{ @*Async sections must have the Async suffix*@
	<div transform-append="tests">RenderAction Async @{Html.RenderAction("Test");}</div>
	<div transform-append="tests">Action Async @Html.Action("Test")</div>
	<p transform-append="message1">Message 1: @ViewBag.Message</p> @*You will see this element blink at the bottom of the body when it arrives. See below for a way to keep it hidden*@
}

@section Message2Async{ @*Async sections must have the Async suffix*@
	<p transform-append="message2" 
		transform-removeClass="hidden" class="hidden"> @*use jsTransform to keep this element hidden until it gets put in its place on the page*@
		Message 2: @ViewBag.Message2</p>
}

<div>Some example footer info</div>

AtlasCode.AsyncSections.Demos/Views/MultipleTask/Test.cshtml
<span>Rendered at @DateTime.Now.ToString()</span>

AtlasCode.AsyncSections.Demos/Views/Progress/Index.cshtml
@{
    ViewBag.Title = "Console";
}

<style>
.hidden
{
	display:none;
}
</style>

<h2>Console Log</h2>

<p>This shows a long running server process feeding back progress as current status</p>

<p>Current Step: <span id="message"></span></p>


@section ConsoleAsync{
<span id="message" transform-replace="message" transform-removeClass="hidden" class="hidden">@ViewBag.Message</span>
}

<div>Some example footer info</div>

AtlasCode.AsyncSections.Demos/Views/ScriptOrder/Index.cshtml
@{
    ViewBag.Title = "Script Ordering";
}

<h2>@ViewBag.Title</h2>

<p>
This demo shows how the developer has fine control over when their javascript gets send to the browser
</p>

<script type="text/javascript">
	alert("Before Async Load");
</script>

@section Task1Async{ @*Async sections must have the Async suffix*@
	<p>@ViewBag.Message</p>
	<script type="text/javascript">
		alert("After Task1 Load");
	</script>
}

@section Task2Async{ @*Async sections must have the Async suffix*@
	<p>@ViewBag.Message2</p>
	<script type="text/javascript">
		alert("After Task2 Load");
	</script>
}

@section scripts{
	<script type="text/javascript">
		alert("After all tasks loaded");
	</script>
}

AtlasCode.AsyncSections.Demos/Views/Shared/_Layout.cshtml
@* Required so you have extention methods for client timings *@
@using StackExchange.Profiling;
<!DOCTYPE html>
<html>
<head>
	@* optional (enable client timing framework) *@ 
    @this.InitClientTimings()
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/themes/base/css", "~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
	<script type="text/javascript" src="@Url.Content("~/Scripts/jsTransform-0.0.1.js")"></script>@* Setup: Add jsTransform *@
</head>
<body>

	<h1>AtlasCode.AsyncSections.Demos</h1>
	<ul>
		<li>@Html.ActionLink("Comparison", "Index", "Comparison")</li>
		<li>@Html.ActionLink("Multiple Tasks", "Index", "MultipleTask")</li>
		<li>@Html.ActionLink("Console", "Index", "Console")</li>
		<li>@Html.ActionLink("Progress", "Index", "Progress")</li>
		<li>@Html.ActionLink("Script Ordering", "Index", "ScriptOrder")</li>
		<li>@Html.ActionLink("Bare Minimum", "Index", "Minimum")</li>
	</ul>

    @Scripts.Render("~/bundles/jquery")
    
	@this.RenderBodyAsync() @* Setup: Change RenderBody to use RenderBodyAsync()*@

	@*From this point down, nothing is send to the browser until all async tasks have completed*@

	@MiniProfiler.RenderIncludes()

	@RenderSection("scripts", required: false)
</body>
</html>

AtlasCode.AsyncSections.Demos/Views/Shared/_Minimum.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Bare Minimum Example</title>
</head>
<body>
	<p>Be sure to include enough content before the RenderBodyAsync() call or IE will not render the page</p>
    @this.RenderBodyAsync()
</body>
</html>